name: Update Composer

on:
  schedule:
    -   cron: '0 7 * * *'
  pull_request:
    branches:
      - master

jobs:
  cucumber-update:
    runs-on: ubuntu-latest
    name: Upstream cucumber update
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --ignore-platform-req=php

      - name: Update cucumber
        run: bin/update_cucumber

      - name: Update translations
        run: bin/update_i18n

      - name: Open a PR
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "Cucumber tag update"
          branch: 'cucumber-update'
          delete-branch: true
          title: 'Cucumber update'
          base: 'master'
