name: Update Composer

on:
  schedule:
    -   cron: '0 7 * * *'
  pull_request:
    branches:
      - master

jobs:
  cucumber-update:
    runs-on: ubuntu-latest
    name: Upstream cucumber update
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --ignore-platform-req=php

      - name: Update cucumber
        run: git config --global user.email "mail@ciaranmcnulty.com" && git config --global user.name "Ciaran McNulty" && bin/update_cucumber
